// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using ProviderOptimizerService.Infrastructure.Data;

#nullable disable

namespace ProviderOptimizerService.Infrastructure.Data.Migrations.EfCore
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("ProviderOptimizerService.Domain.Entities.Provider", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<int>("ActiveAssignments").HasColumnType("integer");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsAvailable").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("PhoneNumber").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<double>("Rating").HasPrecision(3, 2).HasColumnType("numeric(3,2)");
                b.Property<byte[]>("RowVersion").IsConcurrencyToken().ValueGeneratedOnAddOrUpdate().HasColumnType("bytea");
                b.Property<int>("TotalAssignments").HasColumnType("integer");
                b.Property<int>("Type").HasColumnType("integer");
                b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.ToTable("providers");
            });
#pragma warning restore 612, 618
        }
    }
}
